# Generated by Django 6.0 on 2025-12-06 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='live_link',
            field=models.URLField(blank=True, help_text='Required for Web Development projects', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('WEB', 'Web Development'), ('DESIGN', 'Graphic Design')], default='WEB', max_length=10),
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('BRANDING', 'Branding'), ('UIUX', 'UI/UX Design'), ('ECOMMERCE', 'E-Commerce'), ('PORTFOLIO', 'Portfolio Site'), ('PRINT', 'Print & Packaging'), ('SOCIAL', 'Social Media')], max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='color_class',
            field=models.CharField(default='bg-slate-900', help_text="Tailwind class like 'bg-amber-900'", max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/covers/'),
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/gallery/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='portfolio.project')),
            ],
        ),
    ]
