# Generated by Django 6.0 on 2025-12-06 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_project_live_link_project_project_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('BRANDING', 'Branding'), ('UIUX', 'UI/UX Design'), ('ECOMMERCE', 'E-Commerce'), ('WEB_DEV', 'Website Development'), ('PRINT', 'Print & Packaging'), ('SOCIAL', 'Social Media')], max_length=50),
        ),
    ]
